/**
 * Backfill script: populate elevation_m for all rows in postcode_zones where it is NULL.
 *
 * Data source: src/data/postcode-elevations.json
 * Generated by scripts/fetch-elevations.ts using SRTM elevation tiles.
 * Re-run fetch-elevations.ts only if new postcodes are added to the database.
 *
 * Usage:
 *   npx tsx scripts/backfill-elevation.ts
 *
 * Requires DATABASE_URL in .env.
 */

import 'dotenv/config'
import { readFileSync } from 'fs'
import { resolve } from 'path'
import { isNull, eq } from 'drizzle-orm'
import { db } from '../src/db/index.js'
import { postcodeZones } from '../src/db/schema.js'

interface ElevationRecord {
    postcode: string
    lat: number
    lng: number
    elevation_m: number | null
}

function loadElevationLookup(): Map<string, number> {
    const filePath = resolve('src/data/postcode-elevations.json')

    let raw: unknown
    try {
        raw = JSON.parse(readFileSync(filePath, 'utf-8'))
    } catch {
        console.error(`Could not read ${filePath}`)
        console.error('Run scripts/fetch-elevations.ts first to generate this file.')
        process.exit(1)
    }

    const records = raw as ElevationRecord[]
    const lookup = new Map<string, number>()

    for (const record of records) {
        if (record.elevation_m !== null) {
            lookup.set(record.postcode, record.elevation_m)
        }
    }

    return lookup
}

async function backfill(): Promise<void> {
    const elevationLookup = loadElevationLookup()
    console.log(`Loaded ${elevationLookup.size} elevation records from JSON\n`)

    const rows = await db
        .select({
            postcode: postcodeZones.postcode,
        })
        .from(postcodeZones)
        .where(isNull(postcodeZones.elevationM))

    console.log(`Found ${rows.length} rows with null elevation_m`)

    let updated = 0
    let skipped = 0

    for (const row of rows) {
        const elevation = elevationLookup.get(row.postcode)

        if (elevation === undefined) {
            console.warn(`  No elevation data for ${row.postcode} — skipping`)
            skipped++
            continue
        }

        await db
            .update(postcodeZones)
            .set({ elevationM: elevation })
            .where(eq(postcodeZones.postcode, row.postcode))

        console.log(`  ${row.postcode} → ${elevation}m`)
        updated++
    }

    console.log(`
─────────────────────────────────────────
Updated : ${updated} rows
Skipped : ${skipped} rows (no data in JSON)
─────────────────────────────────────────
  `.trim())
}

backfill()
    .then(() => process.exit(0))
    .catch((err) => {
        console.error('Backfill failed:', err)
        process.exit(1)
    })